hotfix/google-analytics-trackID

diff --git a/.github/workflows/dev_campomaq-ec.yml b/.github/workflows/dev_campomaq-ec.yml
--- a/.github/workflows/dev_campomaq-ec.yml
+++ b/.github/workflows/dev_campomaq-ec.yml
@@ -39,7 +39,7 @@ jobs:
       contents: read
     env:
       NEXT_PUBLIC_API_URL_DEV: ${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
-      NEXT_PUBLIC_GA_TRACKING_ID_DEV: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
+      NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
 
     steps:
       - name: Checkout repo
@@ -63,6 +63,13 @@ jobs:
         run: |
           if [ -z "${NEXT_PUBLIC_API_URL_DEV}" ]; then
             echo "::error::NEXT_PUBLIC_API_URL_DEV is not set. Define it as a GitHub Secret or Repository Variable.";
+            exit 1
+          fi
+
+      - name: Validate NEXT_PUBLIC_GA_TRACKING_ID
+        run: |
+          if [ -z "${NEXT_PUBLIC_GA_TRACKING_ID}" ]; then
+            echo "::error::NEXT_PUBLIC_GA_TRACKING_ID is not set. Define it as a GitHub Secret or Repository Variable.";
             exit 1
           fi
 
